Adding check for travis to validate logs

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -1,14 +1,17 @@
 #!/bin/sh
 set -e
 
-mkdir -p bin
-( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )
-git clone https://github.com/snapcore/snapd target
+if [ -f logs/spread.log ]; then
+	cat logs/spread.log
+else
+	echo "spread.log does not exist in logs dir"
+	exit 1
+fi
 
-cd target || exit 1
-
-# TODO: Remove when conjureup snapd is propoted to stable
-sed 's/SNAP\/conjureup/#SNAP\/conjureup/g' -i tests/main/install-snaps/task.yaml
-# TODO: Remove when is fixed the issue raised on https://forum.snapcraft.io/t/error-installing-the-docker-snap-in-fedora-and-opensuse/1655
-sed 's/SNAP\/docker/#SNAP\/docker/g' -i tests/main/install-snaps/task.yaml
-../bin/spread -v linode:tests/main/install-snaps
+if cat logs/spread.log | grep -q "error: unsuccessful run"; then
+	echo "spread tests failed"
+	exit 1
+else
+	echo "spread tests passed"
+	exit 0
+fi
